version: "3"

services:

  caddy:
    build:
      context: ./docker/caddy
    restart: unless-stopped
    command: [ "caddy", "run", "--resume" ]
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"

  composer:
    image: composer
    volumes:
      - ./:/app